### PR TITLE
User permissions docs + Example Genomics Site Building Docs

### LINKED ISSUE #49: Upgrading the Tripal 3 docs surrounding building a site to Tripal 4
Fill out the Building your Site section by transferring over the info from the Tripal 3 docs with updated screenshots and text where things have changed focusing on [Brief Drupal Overview](https://tripal.readthedocs.io/en/latest/user_guide/drupal_overview.html), [Learn Chado](https://tripal.readthedocs.io/en/latest/user_guide/learn_chado.html) (this will be identical), [Working with Content Types](https://tripal.readthedocs.io/en/latest/user_guide/content_types.html), [Setup of an Example Site](https://tripal.readthedocs.io/en/latest/user_guide/example_genomics.html).

### PR DESCRIPTION
**Pull request by pdtouch**
Created documentation for the user permissions pages under site administration.

### CODE REVIEW

**Review by laceysanderson — COMMENTED** [review]
Thanks for the PR and first draft @pdtouch 

Some suggestions/Comments:

It looks like a fair amount of the text is directly copy pasted from Drupal. We will need to reword most of this. That said, we can also be more brief and link there for more details. For example, you could reduce the "What are *?" sections into a single list such as this and then follow up with a short paragraph for best practices (basically your last paragraph under roles).

> - Users: Anyone who visits your site, including you.
> - Permissions: A small group of actions on your site (e.g. import a GFF3 file). These can be granted to specific users or roles.
> - Roles: A group of users such as Anonymous (not logged in) and Authenticated (logged in) Users. Tripal specific examples are 
> Curators or Data Submitters

For the screenshot with permissions for a curator, I would instead highlight specific permissions that are important (i.e. Files, Nodes and Tripal Content). The screenshots are nice but the focus makes it less overwhelming :-) 

Also for permissions, make sure you add a checkmark to the Tripal Content permissions "Access Content Listing", "Create new Tripal Content", "Edit Tripal Content", etc. You could also have a note about site administrators considering whether they want to allow their curators to delete content and if so they need to apply the "Delete Tripal Content" permission. If their curator also imports data via our data importers they may want to assign the Tripal Importer permissions, publish and"Upload Tripal Data files". Things like this are what our docs can offer that the default Drupal ones do not.

**Comment by laceysanderson** [comment]
@pdtouch it looks like the example site building docs ended up in this PR as well since you used the same branch 🙈 This is one of those "features" of git/github that often cause confusion. Once you create a PR it is tied to the branch for the lifetime of the PR. This allows us to update PRs based on review :-) but it also means that if we start working on other functionality we need to make a new branch. This is often missed when people are using their own forks 💞 

I understand that you are working on another project for the next couple of weeks so we'll just leave this all in one. Can you provide a quick update on where you are? perhaps we can review and merge in it's current state?

**Comment by pdtouch** [comment]
> @pdtouch it looks like the example site building docs ended up in this PR as well since you used the same branch 🙈 This is one of those "features" of git/github that often cause confusion. Once you create a PR it is tied to the branch for the lifetime of the PR. This allows us to update PRs based on review :-) but it also means that if we start working on other functionality we need to make a new branch. This is often missed when people are using their own forks 💞
> 
> I understand that you are working on another project for the next couple of weeks so we'll just leave this all in one. Can you provide a quick update on where you are? perhaps we can review and merge in it's current state?

Documentation pages for creating an example site in Tripal 4 has been pushed to 49-addPlaceholderPages. Some functionality of Tripal 3 not yet available in Tripal 4 to my knowledge are mentioned in notes. It can be reviewed and any suggestions to improve can be incorporated. 

Documentation for Users, Permissions and Roles have been added as you mentioned earlier.

Yes, a different branch name for this makes sense.

I think it can be merged if it looks ok. 

Thanks!

**Review by laceysanderson — APPROVED** [review]
Hi Sukha, these changes are looking really good :-) Thank you for all your work on these docs! 

There are a few things that need to be updated so I've changed the merge to allow this to be merged into a different branch then I can make the changes there and make a new PR to get them live. I just figure that will be easier then trying to make a PR to your fork 🙈

**Pull request merged**
