### PR TITLE
Add tables for field naming conventions

### PR DESCRIPTION
**Pull request by Ferrisx4**
Add tables derived from the notes taken during the 2023 Tripal Cofest in San Diego, CA
[Notes](https://docs.google.com/document/d/1oKqSDJpk1OtoyrX0Fp-10ltghpat8W_Bze1Tdegb2Jk/edit# "Notes")

For https://github.com/tripal/tripal_doc/issues/27

### CODE REVIEW

**Comment by Ferrisx4** [comment]
@spficklin These are from some of the notes I took during the cofest. I know you had a number of other changes in mind, but @laceysanderson asked if I could get started with these. I think I have the syntax correct for what we agreed on while @srobb1 was building the field.

**Comment by spficklin** [comment]
Thanks @Ferrisx4 .  I wish I had taken better notes when we were building that field because some of the thoughts I had about what was missing in the documentation have left me.   I need to go back and watch the recording.  But, I don't recall what table this is referring to?  I do remember having a conversation about setting a standard for field naming, but I don't know what is meant by a table.  Do you?

**Comment by Ferrisx4** [comment]
The info from the notes I took best fit in to a pair of tables in the documentation, regarding the naming conventions for the fields files and their annotations, which is what I added.

**Review by laceysanderson — APPROVED** [review]
This matches my remembering of the naming conventions we discussed :-) Thanks @Ferrisx4

**Comment by laceysanderson** [comment]
I'm going to merge this so it's available to others even though @spficklin hasn't gotten the check to verify. I'm sure this is correct but if not we'll just update with another PR.

**Comment by spficklin** [comment]
Sorry, I missed this!  These naming conventions are good for core Tripal fields.  The word "Default" in the naming conventions should be clarified.  It's for core fields, whereas fields in extension modules probably shouldn't use the word "Default"

**Comment by laceysanderson** [comment]
It does say "In addition, for fields that will be included in Tripal Core, note the ‘Default’ designation" currently but we could do another PR to make sure it is really clear (especially for anyone who doesn't read the text but just jumps in to look at the table as a reminder.

**Comment by spficklin** [comment]
Yeah, we might want to make that more clear.

**Pull request merged**
