### PR TITLE
Docmentation for field creation

### PR DESCRIPTION
**Pull request by spficklin**
This PR adds documenation for creation of a field in Tripal v4.  It is complete through creation of the Tripal field type, but still needs to define the Widget and Formatter classes.  Below are screenshots of the docs:

image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by spficklin** [comment]
This PR has been updated as per PR https://github.com/tripal/t4d8/pull/321.

**Comment by laceysanderson** [comment]
Hi @spficklin, I'm not seeing the commit for your recent docs taking into account the change for Issue t4d8#310. Maybe they didn't get pushed?

**Comment by spficklin** [comment]
Hi @laceysanderson since this PR https://github.com/tripal/tripal_doc/pull/17 never got merged I just updated that PR. The updated documentation is there.

**Comment by spficklin** [comment]
I see what went wrong.  I didn't realize you merged in the 4.x branch, I pushed and didn't pay close enough attention to realize the push failed.  It was still sitting there failed on my machine. I fixed it and pushed.  Hopefully it's there now.

**Comment by laceysanderson** [comment]
Yes, it's all there now! I've started looking through it for you :-)

**Comment by spficklin** [comment]
I need to update this with the addition of the terms to the property constructor.  Are you still making addiitons/updates?

**Comment by laceysanderson** [comment]
Not right now :-) Focusing on the tripaldocker + add content page

**Review by laceysanderson — APPROVED** [review]
I'm approving and merging these docs. They don't include the property updates though @spficklin so if you have time to add those then just submit a new PR for them.

**Pull request merged**
